package model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 12 14:26:06 CEST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AdresseVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AdresseVOImpl() {
    }
}

