package model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 12 14:25:43 CEST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContribuableVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ContribuableVOImpl() {
    }

    /**
     * Returns the bind variable value for bdnif.
     * @return bind variable value for bdnif
     */
    public String getbvnif() {
        return (String) getNamedWhereClauseParam("bvnif");
    }

    /**
     * Sets <code>value</code> for bind variable bdnif.
     * @param value value to bind as bdnif
     */
    public void setbvnif(String value) {
        setNamedWhereClauseParam("bvnif", value);
    }
}

